spring:
  application:
    name: void-db-users
  datasource:
    url: jdbc:postgresql://void-db-users-db:5432/void-db
    username: u
    password: p
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
